### ISSUE TITLE
When frozen using py2exe, FileNotFoundError - Lorem ipsum.txt

### ISSUE THREAD

**Issue by marunguy** [jaraco/jaraco.text#11]
* test envrionment
  * windows 10 64bit
  * python 3.10.9 64bit
  * jaraco.text 3.11.0
  * [py2exe](https://github.com/py2exe/py2exe) 0.13.0.0

* When frozen file using py2exe is executed, `FileNotFoundError: D:\test\dist_py2exe_x\test.exe/jaraco/text/Lorem ipsum.txt` occurs.
* `lorem_ipsum` variable seems to be used only at doctest time.
* When frozen, doctest probably won't run.
* When frozen, how about set `lorem_ipsum` variable as an empty string like below?
* below is my test.
* `test.py` source
```python
import jaraco.text

def main() -> None:
    print("main: start")

if __name__ == "__main__":
    main()
```

* `FileNotFoundError` raised
```
D:\test\dist_py2exe_x>test.exe
Traceback (most recent call last):
  File "test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "zipextimporter.pyc", line 167, in exec_module
  File "jaraco\text\__init__.pyc", line 230, in <module>
  File "zipfile.pyc", line 2362, in read_text
  File "zipfile.pyc", line 2342, in open
FileNotFoundError: D:\test\dist_py2exe_x\test.exe/jaraco/text/Lorem ipsum.txt
```
* modify [jaraco.text.__init__.py](https://github.com/jaraco/jaraco.text/blob/main/jaraco/text/__init__.py) line 230
  * from
```python
    lorem_ipsum: str = files(__name__).joinpath('Lorem ipsum.txt').read_text()
```
  * to
```python
...
import sys
...
if not hasattr(sys, 'frozen'):
    lorem_ipsum: str = files(__name__).joinpath('Lorem ipsum.txt').read_text()
else:
    # lorem_ipsum seems to be used only during doctest.
    # It is assumed that doctest doesn't run when frozen using py2exe or pyinstaller.
    lorem_ipsum = ""
```
* run without error
```
D:\test\dist_py2exe_x>test.exe
main: start
```

**Comment by jaraco** [comment]
> * `lorem_ipsum` variable seems to be used only at doctest time.

It's only used at test time by this package, but it is a public attribute, made available to other projects that might need a body of text to test/exercise/demonstrate behavior. Changing the value to be conditionally empty is undesirable, adding variability to an otherwise constant string.

The underlying cause here is that whatever is freezing the modules isn't doing so in a way that's compatible with package resources (as supplied by importlib.resources). Rather than requiring each downstream package with resources to conditionally suppress loading of resources, we should fix the root cause so any package can bundle resources. Ideally, whatever is freezing the module (py2exe in this case) should supply a hook (per [the Extending docs](https://importlib-resources.readthedocs.io/en/latest/using.html#extending)) to ensure that resources are available for the packages they supply.

My recommendation is to file an issue with py2exe and request that they supply this functionality. As maintainer of importlib resources, I'd be happy to consult and help devise a proper solution.
